;=====================================================================
;			MARBLES PROGRAM
;	DESCRIPTION:
;	PUT MARBLES IN CUPS & TAKE THEM OUT
;	THOU MARBLE GODDESS IS A FICKLE MISTRESS
;=====================================================================

	DOSSEG
	.MODEL  LARGE,BASIC
							;PROCEDURES TO
	EXTRN	NEWLINE:FAR		;DISPLAY NEWLINE CHARACTER
	EXTRN	PUTDEC$:FAR		;DISPLAY 16-BIT DECIMAL INTEGER
	EXTRN	PUTSTRNG:FAR	;DISPLAY CHARACTER STRING
	EXTRN	PAUSE:FAR		;DISPLAY CHARACTER STRING
	
;===================================================================
;
; S T A C K   S E G M E N T   D E F I N I T I O N
;
	.STACK  256

;===================================================================
;
; C O N S T A N T   S E G M E N T   D E F I N I T I O N
;
.CODE
.DATA
HEADER		DB	'-----MARBLES-----'
COMMA		DB	', ';3

;DEBUG		DB	'EXECUTED PAST THIS LINE'	;23 CHARS
PAUMSG		DB	'PRESS ANY KEY TO CONTINUE ... '
NAME_IR		DB	'MARBLE PROGRAM - IAN ROSNER'
;===============================================================
;
; D A T A   S E G M E N T   D E F I N I T I O N
;
CUPS		DB	500 DUP (0)
N			DW	1		;N = CUP OFFSET (EVERY CUP, EVERY OTHER, EVERY 3RD)
;===============================================================
;
; C O D E   S E G M E N T   D E F I N I T I O N
;
	.CODE
	;ASSUME DS:NOTHING,ES:DGROUP
STARTUP:
	MOV		AX,DGROUP		;SET ES TO POINT TO DATA SEG
	MOV		ES,AX
	MOV		DS,AX
	
	LEA		DI,HEADER
	MOV		CX,17
	CALL	PUTSTRNG
	CALL	NEWLINE
	
	;WHILE N < 500
	;FOR NTH CUP, XOR
	;N++
	;AX REGISTER IS CURRENT CUP (CUP COUNTER)
MAIN:
	MOV		AX,0			;RESET CUP COUNTER
	
	LOOP1:		;MARBLE EXCHANGE LOOP
		MOV		DI,AX		;CHECK CUP FOR MARBLE -
		XOR		[CUPS+DI],1	;IF IT HAS ONE, TAKE IT OUT
							;IF IT DOESNT, PUT ONE IN

		ADD		AX,N	;ADD CUP OFFSET
		.IF		AX < 500;IF WE DONT EXCEED 500TH CUP
			JMP LOOP1	;PROCEED WITH MARB EXCHANGE
		.ENDIF
						;IF PAST 500, INCREMENT CUP OFFSET
		INC		N
		.IF		N < 500 
			JMP MAIN	;AND PROCEED TO MARB EXCHANGE
		.ENDIF			;IF OFFSET < 500, DROP THROUGH
						;TO PRINT SEGMENT
		
	MOV		AX,0
	MOV		CL,0
	MOV		BH,-1	;LEFT-JUSTIFY PUTDEC
PRINT:
	;FOR I = 0 TO 500,
	;IF I HAS MARB, PRINT I
	;AX CONTAINS COUNT - CUPS[AX]
	MOV		DI,AX
	
	;IF MARBLE IN CUP
	.IF		[CUPS+DI] == 1
		CALL	PUTDEC$	;PRINT CURRENT CUP #
		INC		CX
	.ENDIF
	
	;PRETTY FORMATTING (LINESPACE EVERY 5TH PRINT)
	.IF		CX > 4
		CALL	NEWLINE
		MOV		CX,0
	.ENDIF
	
	INC		AX		;LOAD UP NEXT CUP
	.IF		AX < 500;HAVE WE CHECKED ALL CUPS?
		JMP PRINT
	.ENDIF
DONE:
	CALL	NEWLINE
	CALL	NEWLINE
	LEA		DI,NAME_IR
	MOV		CX,27
	CALL	PUTSTRNG
	CALL	NEWLINE
	LEA		DI,PAUMSG
	MOV		CX,30
	CALL PAUSE

	.EXIT
END STARTUP